version: '3'
services:
  billing_db: 
    image: mysql:8.0.26
    volumes:
      - mysql-billing-data:/var/lib/mysql
      - ./db/billingdb.sql:/docker-entrypoint-initdb.d/billingdb.sql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
  billing_app:
    restart: always
    volumes:
      - ./in:/src/in
    build: .

volumes:
  mysql-billing-data:

# - /home/${USER}/mysql-data:/var/lib/mysql
# FLASK_APP=app.py
# FLASK_ENV=development