version: '3'
services:
  billing_db: 
    image: mysql:8.0.26
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mysql-billing-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
  billing_app:
    restart: always
    volumes:
      - ./in:/src/in
    build: .

volumes:
  mysql-billing-data: