version: '3'
services:
  weight_app:
    volumes:
      - ./app:/app
    ports:
      - "3000:8081"
  sql:
    volumes:
      - ./db/weightdb.sql:/docker-entrypoint-initdb.d/weightdb.sql
      
# docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up --build
